id: 3b0bca0417f24151b4dcb0ee59b853ee
initial_creation_type: ocr
source_metadata:
  volumes:
    276c0540476b4b8c9db2a689ff9724c6:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
